#!/bin/bash

brdexec_proxy__brdexec_init () {

  ### set default for broadexec proxy if missing
  if [ "${BRDEXEC_PROXY}" != "yes" ] && [ "${BRDEXEC_PROXY}" != "no" ]; then
    BRDEXEC_PROXY=yes
  fi
  if [ -z "${BRDEXEC_PROXY}" ]; then
    BRDEXEC_PROXY=yes
  fi
}

brdexec_proxy__brdexec_manipulate_hostfiles () {

  local PROXY_HOSTLIST_DIR

  ### check if hostlist chosen is proxy hostlist
  PROXY_HOSTLIST="$(echo "${BRDEXEC_SERVERLIST_CHOSEN}" | awk -F "/" '{print $NF}' | awk -F "." '{print $1}')"
  if [ "${PROXY_HOSTLIST}" != "all" 2>/dev/null ]; then
    BRDEXEC_PROXY=no
    return 0
  else
    PROXY_HOSTLIST="$(echo "${BRDEXEC_SERVERLIST_CHOSEN}" | awk -F "/" '{print $NF}' | awk -F "." '{print $2}')"
    if [ -z "${PROXY_HOSTLIST}" ]; then
      BRDEXEC_PROXY=no
      return 1
    fi
  fi

  ### check if there are some proxy lists associated
  for PROXY_HOSTLIST_DIR in "${BRDEXEC_DEFAULT_HOSTS_FOLDER}" "${BRDEXEC_DEFAULT_HOSTS_FOLDER}/${BRDEXEC_TEAM_CONFIG}"; do
    for BRDEXEC_POSSIBLE_PROXY_ITEM in $(ls -1 "${PROXY_HOSTLIST_DIR}"); do
      if [ "$(echo "${BRDEXEC_POSSIBLE_PROXY_ITEM}" | awk -F "." '{print $2}')" = "${PROXY_HOSTLIST}" ]; then
        BRDEXEC_POSSIBLE_PROXIES+=" $(echo "${BRDEXEC_POSSIBLE_PROXY_ITEM}" | awk -F "." '{print $1}')"
      fi
    done
  done
}

brdexec_proxy_get_proxy_info () {

  BRDEXEC_PROXY_HOST="$(echo "${BRDEXEC_PROXY_ITEM}" | awk -F "-" '{print $1}')"
  if [ "$(echo "${BRDEXEC_PROXY_HOST}" | grep -c "@")" -eq 1 ]; then
    BRDEXEC_PROXY_HOST="$(echo "${BRDEXEC_PROXY_HOST}" | awk -F "@" '{print $2}')"
  fi
  if [ "$(echo "${BRDEXEC_PROXY_HOST}" | grep -c ":")" -eq 1 ]; then
    BRDEXEC_PROXY_HOST="$(echo "${BRDEXEC_PROXY_HOST}" | awk -F ":" '{print $1}')"
  fi
  BRDEXEC_PROXY_PATH="$(echo "${BRDEXEC_PROXY_ITEM}" | awk -F "-" '{print $2}')"
  BRDEXEC_PROXY_USER="$(echo "${BRDEXEC_PROXY_ITEM}" | awk -F "@" '{print $1}')"
  if [ "${BRDEXEC_PROXY_USER}" = "" ]; then
    BRDEXEC_PROXY_USER="${BRDEXEC_USER}"
  fi
  BRDEXEC_PROXY_PORT="$(echo "${BRDEXEC_PROXY_ITEM}" | awk -F "-" '{print $1}' | awk -F ":" '{print $2}')"
  if [ "${BRDEXEC_PROXY_PORT}" = "" ]; then
    BRDEXEC_PROXY_PORT=22
  fi
}

brdexec_proxy_get_proxy_ip () {

  ### checking hostname against broadexec hosts file
  ### awk is used to find exact match of server name in 2nd field and tail prints last occurence
  if BRDEXEC_TEMP_OUTPUT="$(grep -v "^#" ${BRDEXEC_HOSTS_FILE} | tr '[A-Z]' '[a-z]' | awk -v server="${BRDEXEC_PROXY_HOST}" '($2 == server) {print $1}' | tail -n 1)"; [ ! -z "${BRDEXEC_TEMP_OUTPUT}" ]; then
    BRDEXEC_PROXY_HOST_NAME="${BRDEXEC_PROXY_HOST}"
    BRDEXEC_PROXY_HOST="${BRDEXEC_TEMP_OUTPUT}"
  ### or against ~/.ssh/config
  ### awk is used to find exact match of server name in 2nd field, where 1st field is "Host", then it reads 5 consecutive lines and ifline matches "Hostname" string in the 1st field, it prints 2nd field, where IP is expected; tail prints last occurence
  elif BRDEXEC_TEMP_OUTPUT="$(grep -v "^#" ~/.ssh/config 2>/dev/null | tr '[A-Z]' '[a-z]' | awk -v server=${BRDEXEC_PROXY_HOST} '($1 == "host") && ($2 == server) {for(i=1; i<=5; i++) {getline; if($1=="host"){break;} else if($1=="hostname"){print $2; brea
k;}}}' | tail -n 1)"; [ ! -z "${BRDEXEC_TEMP_OUTPUT}" ]; then
    BRDEXEC_PROXY_HOST_NAME="${BRDEXEC_PROXY_HOST}"
    BRDEXEC_PROXY_HOST="${BRDEXEC_TEMP_OUTPUT}"
  elif BRDEXEC_TEMP_OUTPUT="$(getent hosts "${BRDEXEC_PROXY_HOST}" | awk '{print $1}')"; [ ! -z "${BRDEXEC_TEMP_OUTPUT}" ]; then
    BRDEXEC_PROXY_HOST_NAME="${BRDEXEC_PROXY_HOST}"
    BRDEXEC_PROXY_HOST="${BRDEXEC_TEMP_OUTPUT}"
  fi
}

brdexec_proxy__brdexec_before_ssh () {

  ### populate proxy list
  if [ -f ./etc/proxy_list ]; then
    BRDEXEC_PROXY_LIST="$(cat ./etc/proxy_list | grep -v "^#" | grep -v "^$")"
  else
    BRDEXEC_PROXY=no
    return 0
  fi

  ### check which proxies are required
  BRDEXEC_PROXY_VALID_LIST="$(mktemp /tmp/broadexec.XXXXXXXXXX)"
  if [ "${BRDEXEC_PROXY}" = "yes" ]; then
    for BRDEXEC_PROXY_ITEM in $(echo "${BRDEXEC_PROXY_LIST}"); do
      brdexec_proxy_get_proxy_info
      if [ "$(echo "${BRDEXEC_POSSIBLE_PROXIES}" | grep -wc "${BRDEXEC_PROXY_HOST}")" -eq 1 ]; then
        echo "${BRDEXEC_PROXY_ITEM}" >> ${BRDEXEC_PROXY_VALID_LIST}
      fi
    done
  fi

  ### initiate proxy instances
  for BRDEXEC_PROXY_ITEM in $(cat "${BRDEXEC_PROXY_VALID_LIST}"); do

    brdexec_proxy_get_proxy_info
    brdexec_proxy_get_proxy_ip

    BRDEXEC_PROXY_ERROR_OUTPUT="$(mktemp /tmp/broadexec.XXXXXXXXXX)"
    BRDEXEC_PROXY_MAIN_OUTPUT="$(mktemp /tmp/broadexec.XXXXXXXXXX)"
    BRDEXEC_TEMP_FILES_LIST+=" ${BRDEXEC_PROXY_ERROR_OUTPUT} ${BRDEXEC_PROXY_MAIN_OUTPUT}"

    #FIXME make better way of checking which hostlist is what
    BRDEXEC_PARAMETERS_BACKUP_PROXY="${BRDEXEC_PARAMETERS_BACKUP}"
    BRDEXEC_SELECTED_PARAMETERS_INFO_PROXY="${BRDEXEC_SELECTED_PARAMETERS_INFO}"
    if [ "$(echo "${BRDEXEC_PARAMETERS_BACKUP}" | grep -c "/all.")" -eq 1 ]; then
      BRDEXEC_PARAMETERS_BACKUP_PROXY="$(echo "${BRDEXEC_PARAMETERS_BACKUP}" | sed -e "s#/all.#/${BRDEXEC_PROXY_HOST_NAME}.#g")"
    fi
    if [ "$(echo "${BRDEXEC_SELECTED_PARAMETERS_INFO}" | grep -c "/all.")" -eq 1 ]; then
      BRDEXEC_SELECTED_PARAMETERS_INFO_PROXY="$(echo "${BRDEXEC_SELECTED_PARAMETERS_INFO}" | sed -e "s#/all.#/${BRDEXEC_PROXY_HOST_NAME}.#g")"
    fi

#    echo "echo \"${BRDEXEC_PROXY_PATH}/broadexec.sh ${BRDEXEC_PARAMETERS_BACKUP_PROXY} ${BRDEXEC_SELECTED_PARAMETERS_INFO_PROXY} --external --runid ${RUNID} --batch -qq\" | ssh -p ${BRDEXEC_PROXY_PORT} -o StrictHostKeyChecking=yes -o BatchMode=yes${BRDEXEC_USER_SSH_KEY} -o \"ConnectTimeout=${BRDEXEC_SSH_CONNECTION_TIMEOUT}\" ${BRDEXEC_PROXY_USER}@${BRDEXEC_PROXY_HOST} \"cat > /tmp/${BRDEXEC_RUNID}_external.sh && chmod +x /tmp/${BRDEXEC_RUNID}_external.sh && /tmp/${BRDEXEC_RUNID}_external.sh; rm /tmp/${BRDEXEC_RUNID}_external.sh\" 2>>${BRDEXEC_PROXY_ERROR_OUTPUT} >> ${BRDEXEC_PROXY_MAIN_OUTPUT} &"
#exit
#    echo "${BRDEXEC_PROXY_PATH}/broadexec.sh ${BRDEXEC_PARAMETERS_BACKUP_PROXY} ${BRDEXEC_SELECTED_PARAMETERS_INFO_PROXY} --external --runid ${RUNID} --batch -qq" | ssh -p ${BRDEXEC_PROXY_PORT} -o StrictHostKeyChecking=yes -o BatchMode=yes${BRDEXEC_USER_SSH_KEY} -o "ConnectTimeout=${BRDEXEC_SSH_CONNECTION_TIMEOUT}" ${BRDEXEC_PROXY_USER}@${BRDEXEC_PROXY_HOST} "cat > /tmp/${BRDEXEC_RUNID}_external.sh && chmod +x /tmp/${BRDEXEC_RUNID}_external.sh && /tmp/${BRDEXEC_RUNID}_external.sh; rm /tmp/${BRDEXEC_RUNID}_external.sh" 2>>${BRDEXEC_PROXY_ERROR_OUTPUT} >> ${BRDEXEC_PROXY_MAIN_OUTPUT} &

    unset BRDEXEC_PROXY_LIST_TO_BE_COPIED
    for PROXY_HOSTLIST_DIR in "${BRDEXEC_DEFAULT_HOSTS_FOLDER}" "${BRDEXEC_DEFAULT_HOSTS_FOLDER}/${BRDEXEC_TEAM_CONFIG}"; do
      for BRDEXEC_POSSIBLE_PROXY_ITEM in $(ls -1 "${PROXY_HOSTLIST_DIR}"); do
echo "P $(echo "${BRDEXEC_POSSIBLE_PROXY_ITEM}" | awk -F "." '{print $1}') PH ${BRDEXEC_PROXY_HOST_NAME}"
        if [ "$(echo "${BRDEXEC_POSSIBLE_PROXY_ITEM}" | awk -F "." '{print $1}')" = "${BRDEXEC_PROXY_HOST_NAME}" ]; then
          BRDEXEC_PROXY_LIST_TO_BE_COPIED="${PROXY_HOSTLIST_DIR}/${BRDEXEC_POSSIBLE_PROXY_ITEM}"
          break
        fi
      done
      if [ ! -z "${BRDEXEC_PROXY_LIST_TO_BE_COPIED}" ]; then
        break
      fi
    done

echo "HOSTLIST ${BRDEXEC_PROXY_LIST_TO_BE_COPIED}"

    BRDEXEC_TARDIR="$(mktemp /tmp/broadexec.XXXXXXXXXX)"

echo "    tar czf - \
      conf/broadexec.conf \
      ${BRDEXEC_PROXY_LIST_TO_BE_COPIED} \
      ${BRDEXEC_SCRIPT_TO_RUN} | \
      ssh \
          -p ${BRDEXEC_PROXY_PORT} \
          -o StrictHostKeyChecking=yes \
          -o BatchMode=yes${BRDEXEC_USER_SSH_KEY} \
          -o \"ConnectTimeout=${BRDEXEC_SSH_CONNECTION_TIMEOUT}\" \
        ${BRDEXEC_PROXY_USER}@${BRDEXEC_PROXY_HOST} \" \
          mkdir -p $BRDEXEC_TARDIR; \
          echo 'Broadexec version:${BRDEXEC_VERSION}' \> ${BRDEXEC_TARDIR}/version_orig; \
          ${BRDEXEC_PROXY_PATH}/broadexec.sh --version \> ${BRDEXEC_TARDIR}/version_target; \
          diff ${BRDEXEC_TARDIR}/version_orig ${BRDEXEC_TARDIR}/version_target 2\>/dev/null \>/dev/null; \
          cat - > ${BRDEXEC_TARDIR}/broadexec_proxy.tar.gz; \
          tar xzf broadexec_proxy.tar.gz -C ${BRDEXEC_PROXY_PATH}/; \
          ${BRDEXEC_PROXY_PATH}/broadexec.sh \
            ${BRDEXEC_PARAMETERS_BACKUP_PROXY} \
            ${BRDEXEC_SELECTED_PARAMETERS_INFO_PROXY} \
            --external \
            --runid ${RUNID} \
            --batch \
            -qq; \
      \" 2>>${BRDEXEC_PROXY_ERROR_OUTPUT} >> ${BRDEXEC_PROXY_MAIN_OUTPUT} &"


    tar czf - \
      conf/broadexec.conf \
      ${BRDEXEC_PROXY_LIST_TO_BE_COPIED} \
      ${BRDEXEC_SCRIPT_TO_RUN} | \
      ssh \
          -p ${BRDEXEC_PROXY_PORT} \
          -o StrictHostKeyChecking=yes \
          -o BatchMode=yes${BRDEXEC_USER_SSH_KEY} \
          -o "ConnectTimeout=${BRDEXEC_SSH_CONNECTION_TIMEOUT}" \
        ${BRDEXEC_PROXY_USER}@${BRDEXEC_PROXY_HOST} " \
          mkdir -p $BRDEXEC_TARDIR; \
          echo 'Broadexec version: ${BRDEXEC_VERSION}' > ${BRDEXEC_TARDIR}/version_orig; \
          ${BRDEXEC_PROXY_PATH}/broadexec.sh --version > ${BRDEXEC_TARDIR}/version_target; \
          diff ${BRDEXEC_TARDIR}/version_orig ${BRDEXEC_TARDIR}/version_target 2>/dev/null >/dev/null; \
          if [ \"\$?\" -ne 0 ]; then \
            >&2 echo \"ERROR: Broadexec version on \$HOSTNAME does not match!\"; \
            rm -rf ${BRDEXEC_TARDIR}; \
            exit 15; \
          fi; \
          cat - > ${BRDEXEC_TARDIR}/broadexec_proxy.tar.gz; \
          tar xzf broadexec_proxy.tar.gz -C ${BRDEXEC_PROXY_PATH}/; \
          ${BRDEXEC_PROXY_PATH}/broadexec.sh \
            ${BRDEXEC_PARAMETERS_BACKUP_PROXY} \
            ${BRDEXEC_SELECTED_PARAMETERS_INFO_PROXY} \
            --external \
            --runid ${RUNID} \
            --batch \
            -qq; \
      " 2>>${BRDEXEC_PROXY_ERROR_OUTPUT} >> ${BRDEXEC_PROXY_MAIN_OUTPUT} &
#rm -rf ${BRDEXEC_TARDIR}; \
#  rm -f \${BRDEXEC_TARDIR}/broadexec_proxy.tar.gz \
#          if [ \"\$?\" -ne 0 ]; then \
#            >&2 echo \"ERROR: Broadexec version on \$HOSTNAME does not match!\"; \
#            rm -rf ${BRDEXEC_TARDIR}; \
#            exit 15; \
#          fi; \

    BRDEXEC_PROXY_PID="${!}"
#echo "Proxy pid: ${BRDEXEC_PROXY_PID}"
    BRDEXEC_PROXY_PIDS+=" ${BRDEXEC_PROXY_PID}"
#echo "PROXY initiated with PID $BRDEXEC_PROXY_PID"
    BRDEXEC_PROXY_MAIN_OUTPUT_ARRAY[$BRDEXEC_PROXY_PID]="${BRDEXEC_PROXY_MAIN_OUTPUT}"
    BRDEXEC_PROXY_ERROR_OUTPUT_ARRAY[$BRDEXEC_PROXY_PID]="${BRDEXEC_PROXY_ERROR_OUTPUT}"
    BRDEXEC_PROXY_HOSTNAME_ARRAY[$BRDEXEC_PROXY_PID]="${BRDEXEC_PROXY_HOST}"
    BRDEXEC_PROXY_USER_ARRAY[$BRDEXEC_PROXY_PID]="${BRDEXEC_PROXY_USER}"
    BRDEXEC_PROXY_PATH_ARRAY[$BRDEXEC_PROXY_PID]="${BRDEXEC_PROXY_PATH}"
    BRDEXEC_PROXY_PORT_ARRAY[$BRDEXEC_PROXY_PID]="${BRDEXEC_PROXY_PORT}"
  done

  ### loop through proxy instances and wait until they are finished
  BRDEXEC_START_TIME=$(date +%s)
  local BRDEXEC_PROXY_DEATH_COUNTER="$(expr $(date +%s) - 900)" #FIXME set proper variable for timeout in config
  local BRDEXEC_PROXY_PID_TOTAL_COUNT="$(echo ${BRDEXEC_PROXY_PIDS}) | wc -w)"
  ### initial line of overall status
  echo "Total: gathering data..."
  while [ "${BRDEXEC_PROXY_DEATH_COUNTER}" -lt "${BRDEXEC_START_TIME}" ]; do
    local BRDEXEC_PROXY_DEATH_COUNTER="$(expr $(date +%s) - 900)" #FIXME set proper variable for timeout in config

    ### get total progress data
    if [ ! -z "${BRDEXEC_CURRENT_STATS_FILE_NUM_TOTAL_SUM}" ]; then
      tput cuu1

      tput el
      echo "Total: ${BRDEXEC_CURRENT_STATS_FILE_NUM_DONE_SUM}/${BRDEXEC_CURRENT_STATS_FILE_NUM_TOTAL_SUM}"

      #reset values
      BRDEXEC_CURRENT_STATS_FILE_NUM_DONE_SUM=0
      BRDEXEC_CURRENT_STATS_FILE_NUM_TOTAL_SUM=0

    fi

    BRDEXEC_PROXY_PID_TOTAL_COUNT="$(echo ${BRDEXEC_PROXY_PIDS} | wc -w)"
    BRDEXEC_PROXY_PID_TOTAL_FINISHED=0
    for BRDEXEC_PROXY_PID in ${BRDEXEC_PROXY_PIDS}; do
      if [ "${BRDEXEC_PROXY_ALREADY_FINISHED_ARRAY[$BRDEXEC_PROXY_PID]}" = "yes" ]; then
        ((BRDEXEC_PROXY_PID_TOTAL_FINISHED++))
      fi

      ### display progress
#echo "STATSFILE ${BRDEXEC_PROXY_STATS_FILE_ARRAY[$BRDEXEC_PROXY_PID]}"
#cat ${BRDEXEC_PROXY_MAIN_OUTPUT_ARRAY[$BRDEXEC_PROXY_PID]}
#ls -la ${BRDEXEC_PROXY_MAIN_OUTPUT_ARRAY[$BRDEXEC_PROXY_PID]}

      if [ -z "${BRDEXEC_PROXY_STATS_FILE_ARRAY[$BRDEXEC_PROXY_PID]}" ]; then
        if [ -f "${BRDEXEC_PROXY_MAIN_OUTPUT_ARRAY[$BRDEXEC_PROXY_PID]}" ]; then
          BRDEXEC_PROXY_STATS_FILE_ARRAY[$BRDEXEC_PROXY_PID]="$(cat ${BRDEXEC_PROXY_MAIN_OUTPUT_ARRAY[$BRDEXEC_PROXY_PID]} | head -n 1)"

#echo "====="
#echo "$(cat ${BRDEXEC_PROXY_MAIN_OUTPUT_ARRAY[$BRDEXEC_PROXY_PID]})"
        fi
#echo "MAIN_OUT: ${BRDEXEC_PROXY_MAIN_OUTPUT_ARRAY[$BRDEXEC_PROXY_PID]}"
#cat ${BRDEXEC_PROXY_MAIN_OUTPUT_ARRAY[$BRDEXEC_PROXY_PID]}
#echo "::: ${BRDEXEC_PROXY_STATS_FILE_ARRAY[$BRDEXEC_PROXY_PID]}"
#echo "ERROR ${BRDEXEC_PROXY_ERROR_OUTPUT_ARRAY[$BRDEXEC_PROXY_PID]}"
#cat ${BRDEXEC_PROXY_ERROR_OUTPUT_ARRAY[$BRDEXEC_PROXY_PID]}
      fi

      unset BRDEXEC_CURRENT_STATS_FILE
      unset BRDEXEC_CURRENT_STATS_FILE_PROGRESS
      unset BRDEXEC_CURRENT_STATS_FILE_STATE
      unset BRDEXEC_CURRENT_STATS_FILE_ERROR
      unset BRDEXEC_CURRENT_STATS_FILE_NUM_DONE
      unset BRDEXEC_CURRENT_STATS_FILE_NUM_TOTAL
      if [ ! -z "${BRDEXEC_PROXY_STATS_FILE_ARRAY[$BRDEXEC_PROXY_PID]}" ]; then

#echo "STATS file, ${BRDEXEC_PROXY_PORT_ARRAY[$BRDEXEC_PROXY_PID]}, ${BRDEXEC_USER_SSH_KEY}, ${BRDEXEC_SSH_CONNECTION_TIMEOUT}, ${BRDEXEC_PROXY_USER_ARRAY[$BRDEXEC_PROXY_PID]}, ${BRDEXEC_PROXY_HOSTNAME_ARRAY[$BRDEXEC_PROXY_PID]}, ${BRDEXEC_PROXY_PATH_ARRAY[$BRDEXEC_PROXY_PID]}, ${BRDEXEC_PROXY_STATS_FILE_ARRAY[$BRDEXEC_PROXY_PID]}"
#echo "ssh -p ${BRDEXEC_PROXY_PORT_ARRAY[$BRDEXEC_PROXY_PID]} -o StrictHostKeyChecking=yes -o BatchMode=yes${BRDEXEC_USER_SSH_KEY} -o \"ConnectTimeout=${BRDEXEC_SSH_CONNECTION_TIMEOUT}\" ${BRDEXEC_PROXY_USER_ARRAY[$BRDEXEC_PROXY_PID]}@${BRDEXEC_PROXY_HOSTNAME_ARRAY[$BRDEXEC_PROXY_PID]} \"cat ${BRDEXEC_PROXY_PATH_ARRAY[$BRDEXEC_PROXY_PID]}/${BRDEXEC_PROXY_STATS_FILE_ARRAY[$BRDEXEC_PROXY_PID]}\""

        BRDEXEC_CURRENT_STATS_FILE="$(ssh -p ${BRDEXEC_PROXY_PORT_ARRAY[$BRDEXEC_PROXY_PID]} -o StrictHostKeyChecking=yes -o BatchMode=yes${BRDEXEC_USER_SSH_KEY} -o "ConnectTimeout=${BRDEXEC_SSH_CONNECTION_TIMEOUT}" ${BRDEXEC_PROXY_USER_ARRAY[$BRDEXEC_PROXY_PID]}@${BRDEXEC_PROXY_HOSTNAME_ARRAY[$BRDEXEC_PROXY_PID]} "cat ${BRDEXEC_PROXY_PATH_ARRAY[$BRDEXEC_PROXY_PID]}/${BRDEXEC_PROXY_STATS_FILE_ARRAY[$BRDEXEC_PROXY_PID]}" 2>/dev/null)"
        if [ "${?}" -ne 0 ]; then
#          tput el
          echo "${BRDEXEC_PROXY_HOSTNAME_ARRAY[$BRDEXEC_PROXY_PID]}: SSH error"
          BRDEXEC_CURRENT_STATS_FILE_ERROR="yes"
        else
          BRDEXEC_CURRENT_STATS_FILE_PROGRESS="$(echo "${BRDEXEC_CURRENT_STATS_FILE}" | grep "^PROGRESS" | awk '{print $4}')"
          BRDEXEC_CURRENT_STATS_FILE_STATE="$(echo "${BRDEXEC_CURRENT_STATS_FILE}" | grep "^STATE" | awk '{print $2}')"

          BRDEXEC_CURRENT_STATS_FILE_NUM_TOTAL="$(echo "${BRDEXEC_CURRENT_STATS_FILE}" | grep "^PROGRESS" | awk '{print $3}')"
          ((BRDEXEC_CURRENT_STATS_FILE_NUM_TOTAL_SUM+=BRDEXEC_CURRENT_STATS_FILE_NUM_TOTAL))
          BRDEXEC_CURRENT_STATS_FILE_NUM_DONE="$(echo "${BRDEXEC_CURRENT_STATS_FILE}" | grep "^PROGRESS" | awk '{print $2}')"
          if [ "${BRDEXEC_CURRENT_STATS_FILE_STATE}" = "FINISHED" ]; then
            BRDEXEC_CURRENT_STATS_FILE_NUM_DONE="${BRDEXEC_CURRENT_STATS_FILE_NUM_TOTAL}"
          fi
          ((BRDEXEC_CURRENT_STATS_FILE_NUM_DONE_SUM+=BRDEXEC_CURRENT_STATS_FILE_NUM_DONE))
      #if [ "$(echo "$BRDEXEC_CURRENT_STATS_FILE" | grep -c "^ssh:")" -gt 0 ]; then
      #  echo "${BRDEXEC_PROXY_HOSTNAME_ARRAY[$BRDEXEC_PROXY_PID]}: SSH error"
      #else
          tput el
          echo "${BRDEXEC_PROXY_HOSTNAME_ARRAY[$BRDEXEC_PROXY_PID]}: ${BRDEXEC_CURRENT_STATS_FILE_PROGRESS}"
        fi
      else
        tput el
        echo "${BRDEXEC_PROXY_HOSTNAME_ARRAY[$BRDEXEC_PROXY_PID]}: no data received"
      fi

    done

    BRDEXEC_PROXY_RUN_FINISHED=0
    for BRDEXEC_PROXY_PID in ${BRDEXEC_PROXY_PIDS}; do
      ps -p ${BRDEXEC_PROXY_PID} >/dev/null
      if [ "$?" -ne 0 ] && [ -z "${BRDEXEC_CURRENT_STATS_FILE_STATE}" ]; then
        BRDEXEC_CURRENT_STATS_FILE_STATE="PROXY_ERROR"
      fi
      if [ "${BRDEXEC_CURRENT_STATS_FILE_STATE}" = "FINISHED" ] || [ "${BRDEXEC_CURRENT_STATS_FILE_STATE}" = "INTERRUPTED" ] || [ "${BRDEXEC_CURRENT_STATS_FILE_STATE}" = "PROXY_ERROR" ] || [ "${BRDEXEC_CURRENT_STATS_FILE_ERROR}" = "yes" ]; then
      ((BRDEXEC_PROXY_RUN_FINISHED++))
      #if [ "${BRDEXEC_PROXY_ALREADY_FINISHED_ARRAY[$BRDEXEC_PROXY_PID]}" != "yes" ]; then
        #ps -p ${BRDEXEC_PROXY_PID} >/dev/null
        #if [ "$?" -ne 0 ]; then
        #  BRDEXEC_PROXY_ALREADY_FINISHED_ARRAY[$BRDEXEC_PROXY_PID]="yes"
        #fi
      #fi
      fi
    done

    if [ "${BRDEXEC_PROXY_RUN_FINISHED}" -eq "${BRDEXEC_PROXY_PID_TOTAL_COUNT}" ]; then
      BRDEXEC_DEATH_COUNTER=${BRDEXEC_START_TIME}
      break
    fi

    ### reset display position
    for useless_counter in $(seq $BRDEXEC_PROXY_PID_TOTAL_COUNT); do
      tput cuu1
#echo >/dev/null
    done

    ### easing demand for CPU in compatible way
    sleep 0.2 2>/dev/null || sleep 1
  done
}

brdexec_proxy__brdexec_display_main_output () {

  for BRDEXEC_PROXY_PID in ${BRDEXEC_PROXY_PIDS}; do
    unset BRDEXEC_PROXY_OUTPUT_REPORT
    BRDEXEC_PROXY_OUTPUT_REPORT="$(cat ${BRDEXEC_PROXY_MAIN_OUTPUT_ARRAY[$BRDEXEC_PROXY_PID]} | grep "^REPORT_FILE" | awk '{print $2}')"
#echo "OUT $BRDEXEC_PROXY_OUTPUT_REPORT ${BRDEXEC_PROXY_MAIN_OUTPUT_ARRAY[$BRDEXEC_PROXY_PID]}"
    if [ ! -z "${BRDEXEC_PROXY_OUTPUT_REPORT}" ]; then
      # i know, genius var name :/
      BRDEXEC_PROXY_OUTPUT_REPORT_OUTPUT="$(ssh -p ${BRDEXEC_PROXY_PORT_ARRAY[$BRDEXEC_PROXY_PID]} -o StrictHostKeyChecking=yes -o BatchMode=yes${BRDEXEC_USER_SSH_KEY} -o "ConnectTimeout=${BRDEXEC_SSH_CONNECTION_TIMEOUT}" ${BRDEXEC_PROXY_USER_ARRAY[$BRDEXEC_PROXY_PID]}@${BRDEXEC_PROXY_HOSTNAME_ARRAY[$BRDEXEC_PROXY_PID]} "cat ${BRDEXEC_PROXY_PATH_ARRAY[$BRDEXEC_PROXY_PID]}/${BRDEXEC_PROXY_OUTPUT_REPORT}" 2>/dev/null )"
      if [ "${?}" -eq 0 ]; then
        if [ ! -z "${BRDEXEC_PROXY_OUTPUT_REPORT_OUTPUT}" ]; then
          echo -e "${BRDEXEC_PROXY_OUTPUT_REPORT_OUTPUT}"
        fi
      fi
    fi

#echo "PID $BRDEXEC_PROXY_PID"
#    echo "${BRDEXEC_PROXY_MAIN_OUTPUT_ARRAY[$BRDEXEC_PROXY_PID]}"
#cat ${BRDEXEC_PROXY_MAIN_OUTPUT_ARRAY[$BRDEXEC_PROXY_PID]}
  done
}

brdexec_proxy__brdexec_generate_error_log () {

  for BRDEXEC_PROXY_PID in ${BRDEXEC_PROXY_PIDS}; do
    unset BRDEXEC_PROXY_ERROR_REPORT
    BRDEXEC_PROXY_ERROR_REPORT="$(cat ${BRDEXEC_PROXY_MAIN_OUTPUT_ARRAY[$BRDEXEC_PROXY_PID]} | grep "^REPORT_ERROR" | awk '{print $2}')"
    if [ ! -z "${BRDEXEC_PROXY_ERROR_REPORT}" ]; then
      BRDEXEC_PROXY_ERROR_REPORT_OUTPUT="$(ssh -p ${BRDEXEC_PROXY_PORT_ARRAY[$BRDEXEC_PROXY_PID]} -o StrictHostKeyChecking=yes -o BatchMode=yes${BRDEXEC_USER_SSH_KEY} -o "ConnectTimeout=${BRDEXEC_SSH_CONNECTION_TIMEOUT}" ${BRDEXEC_PROXY_USER_ARRAY[$BRDEXEC_PROXY_PID]}@${BRDEXEC_PROXY_HOSTNAME_ARRAY[$BRDEXEC_PROXY_PID]} "cat ${BRDEXEC_PROXY_PATH_ARRAY[$BRDEXEC_PROXY_PID]}/${BRDEXEC_PROXY_ERROR_REPORT}" 2>/dev/null )"
      if [ "${?}" -eq 0 ]; then
        if [ ! -z "${BRDEXEC_PROXY_ERROR_REPORT_OUTPUT}" ]; then
          echo "${BRDEXEC_PROXY_ERROR_REPORT_OUTPUT}" >> ${BRDEXEC_REPORT_ERROR_FILE}
          echo "${BRDEXEC_PROXY_ERROR_REPORT_OUTPUT}" >> ${BRDEXEC_MAIN_ERROR_CURLOG}
        fi
      fi
    fi
  done
}
